CREATE TABLE SALESPERSON
(
    Sid INT NOT NULL AUTO_INCREMENT,
    Sname VARCHAR(20) NOT NULL,
PRIMARY KEY (Sid)
);

CREATE TABLE VEHICLE_INFO
(
    INFO_ID INT NOT NULL AUTO_INCREMENT,
    Company VARCHAR(20) NOT NULL,
    Model_Name VARCHAR(20) NOT NULL,
    Engine_Capacityex INT,
    Tonnage INT,
    Color VARCHAR(20) NOT NULL,
    Year INT NOT NULL,
PRIMARY KEY(INFO_ID)
);

CREATE TABLE VEHICLE
(
    Vin VARCHAR(20) NOT NULL,
    Price INT NOT NULL,
    Saled Boolean NOT NULL,
    Vehicle_Info_Id INT NOT NULL,
PRIMARY KEY (Vin),
FOREIGN KEY (Vehicle_Info_Id) REFERENCES VEHICLE_INFO(INFO_ID) -- 자동차 정보 테이블과 1:1 관계
);

CREATE TABLE CUSTOMER
(
    Ssn INT NOT NULL AUTO_INCREMENT,
    Cname VARCHAR(20) NOT NULL,
    City VARCHAR(20) NOT NULL,
    Street VARCHAR(20) NOT NULL,
    Detail_Address VARCHAR(50),
PRIMARY KEY(Ssn)
);

CREATE TABLE SALE
(
    Sale_Id INT NOT NULL AUTO_INCREMENT,
    SSid INT NOT NULL,
    SVin VARCHAR(20) NOT NULL,
    SSsn INT,
    BookDate Date, -- Customer의 예약 날짜 (오기로 약속한 날짜)
PRIMARY KEY (Sale_Id),
FOREIGN KEY (SSid) REFERENCES SALESPERSON(Sid),
FOREIGN KEY (SVin) REFERENCES VEHICLE(Vin),
FOREIGN KEY (SSsn) REFERENCES CUSTOMER(Ssn)
);
-- 판매 중 : SSsn이 NULL / 예약 완료 : SSsn이 NOT NULL / 판매 완료 : 데이터 삭제됨

CREATE TABLE USER
(
    Usn INT NOT NULL AUTO_INCREMENT,
    User_Id VARCHAR(20) NOT NULL,
    Password VARCHAR(20) NOT NULL,
    Uid INT NOT NULL,
    Role VARCHAR(20) NOT NULL,
PRIMARY KEY (Usn),
FOREIGN KEY (Uid) REFERENCES CUSTOMER(Ssn),
FOREIGN KEY (Uid) REFERENCES SALESPERSON(Sid)
);